<a href="https://colab.research.google.com/github/shohruhinomjonov691-hub/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import pandas as pd

In [11]:
print(pd.__version__)

2.2.2

In [12]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [13]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [14]:
df.tail(-1) # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [17]:
df.shape

(7, 2)

In [16]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [18]:
df.dtypes

cars      object
counts     int64
dtype: object

In [20]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [21]:
df.describe() #numerical columns only

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [23]:
df.iloc[2:] # 1:4, 0, 2

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [26]:
df.loc[2:5, "cars"] # [:, "counts"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [27]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [28]:
df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [30]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [33]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [34]:
df.min()

cars      BMW
counts      1
dtype: object

In [35]:
df.max()

cars      Volvo
counts        9
dtype: object

In [36]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [37]:
df.count()

cars      7
counts    7
dtype: int64

In [38]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [39]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Ford", "Tesla", "Ferrari", None, "BMW"],
    "counts": [3, None, 2, 8, None, 1, 9, 3]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     NaN
2     None     2.0
3     Ford     8.0
4    Tesla     NaN
5  Ferrari     1.0
6     None     9.0
7      BMW     3.0

In [41]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [43]:
df_missing.dropna(subset=['counts']) # how="all", axis=1, subset=['counts'],

      cars  counts
0      BMW     3.0
2     None     2.0
3     Ford     8.0
5  Ferrari     1.0
6     None     9.0
7      BMW     3.0

In [44]:
df_missing.fillna({'cars': 'unknown', "counts": 0}) # unknown,

      cars  counts
0      BMW     3.0
1    Volvo     0.0
2  unknown     2.0
3     Ford     8.0
4    Tesla     0.0
5  Ferrari     1.0
6  unknown     9.0
7      BMW     3.0

In [52]:
# df = pd.read_csv("Titanic-Dataset.csv")

# df.head(30)
df = pd.read_excel("test.xlsx")
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [51]:
df.to_excel("test.xlsx")

In [53]:
# Series => 10
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [54]:
car_series = data_with_missing['cars']
print(car_series)

['BMW', 'Volvo', None, 'Ford', 'Tesla', 'Ferrari', None, 'BMW']